"use strict";
module.exports = {
  up: async (queryInterface, DataTypes) => {
    await queryInterface.bulkInsert(
      "brands",
      [
        {
          uuid: "1f26e9b2-d1c3-474b-9a17-b494ab85cead",
          code: "909002342923",
          name_tm: "Nike",
          name_ru: "Nike",
          name_en: "Nike",
          image_isAdded: true,
          canPublished: true,
          isActive: true,
          createdAt: DataTypes.fn("now"),
          updatedAt: DataTypes.fn("now"),
        },
        {
          uuid: "6dc7cfed-b3c3-4e8f-897d-e7146de7f99c",
          code: "909233452300923234",
          name_tm: "Taze Ay",
          name_ru: "Taze Ay",
          name_en: "Taze Ay",
          image_isAdded: true,
          canPublished: true,
          isActive: true,
          createdAt: DataTypes.fn("now"),
          updatedAt: DataTypes.fn("now"),
        },
        {
          uuid: "a5b78855-5e1c-48cd-ac83-bab49c87c1f7",
          code: "2334534234",
          name_tm: "Ak Bulut",
          name_ru: "Ak Bulut",
          name_en: "Ak Bulut",
          image_isAdded: true,
          canPublished: true,
          isActive: true,
          createdAt: DataTypes.fn("now"),
          updatedAt: DataTypes.fn("now"),
        },
        {
          uuid: "e37f9d04-179e-402e-93bd-3611946ad347",
          code: "12334576123",
          name_tm: "Tac Hil",
          name_ru: "Tac Hil",
          name_en: "Tac Hil",
          image_isAdded: true,
          canPublished: true,
          isActive: true,
          createdAt: DataTypes.fn("now"),
          updatedAt: DataTypes.fn("now"),
        },
        {
          uuid: "ea69248e-f7c2-4df5-97f3-3ecbdb28a439",
          code: "1231567523",
          name_tm: "Yupekci",
          name_ru: "Yupekci",
          name_en: "Yupekci",
          image_isAdded: true,
          canPublished: true,
          isActive: true,
          createdAt: DataTypes.fn("now"),
          updatedAt: DataTypes.fn("now"),
        },
        {
          uuid: "71967c2c-e76e-487f-ac5b-80733b351aff",
          code: "2342567534",
          name_tm: "Nestle",
          name_ru: "Nestle",
          name_en: "Nestle",
          image_isAdded: true,
          canPublished: true,
          isActive: true,
          createdAt: DataTypes.fn("now"),
          updatedAt: DataTypes.fn("now"),
        },
        {
          uuid: "b18c796d-53dd-4a0b-9463-de25ac611483",
          code: "23456756234",
          name_tm: "Wegmans",
          name_ru: "Wegmans",
          name_en: "Wegmans",
          image_isAdded: true,
          canPublished: true,
          isActive: true,
          createdAt: DataTypes.fn("now"),
          updatedAt: DataTypes.fn("now"),
        },
        {
          uuid: "b6d69c93-2bb4-4988-9f6c-c65c791b71b0",
          code: "234234287678543",
          name_tm: "Nescafe",
          name_ru: "Nescafe",
          name_en: "Nescafe",
          image_isAdded: true,
          canPublished: true,
          isActive: true,
          createdAt: DataTypes.fn("now"),
          updatedAt: DataTypes.fn("now"),
        },
        {
          uuid: "d069f103-7e9c-45e2-970a-77aba6249a9f",
          code: "123246453456",
          name_tm: "TM Limited",
          name_ru: "TM Limited",
          name_en: "TM Limited",
          image_isAdded: true,
          canPublished: true,
          isActive: true,
          createdAt: DataTypes.fn("now"),
          updatedAt: DataTypes.fn("now"),
        },
        {
          uuid: "210798a8-3f51-4a5b-8233-fd69fbe8a465",
          code: "789723489867545",
          name_tm: "Gala",
          name_ru: "Gala",
          name_en: "Gala",
          image_isAdded: true,
          canPublished: true,
          isActive: true,
          createdAt: DataTypes.fn("now"),
          updatedAt: DataTypes.fn("now"),
        },
      ],
      {}
    );
  },

  down: async (queryInterface, DataTypes) => {
    await queryInterface.bulkDelete("brands", null, {});
  },
};
